image: hashicorp/terraform:latest

pipelines:
  branches:
    "{feature/*,bugfix/*,develop}":
      - step:
          name: Deploy Infrastructure (Dev)
          caches:
            - terraform
          script:
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION="us-east-1"
            - ./scripts/deploy.sh dev

    test:
      - step:
          name: Deploy Infrastructure (Stage)
          caches:
            - terraform
          script:
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION="us-east-1"
            - ./scripts/deploy.sh stage

    master:
      - step:
          name: Deploy Infrastructure (Prod)
          caches:
            - terraform
          script:
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION="us-east-1"
            - ./scripts/deploy.sh prod
